apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: kevinyu0506/gitops-demo-backend
        name: backend
        ports:
        - containerPort: 5000
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 2

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
